Erkan.ToDo.Web/Areas/Admin/Controllers/GraphicController.cs
using Erkan.ToDo.Business.Abstract;
using Erkan.ToDo.Web.StringInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Erkan.ToDo.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = RoleInfo.Admin)]
    [Area(AreaInfo.Admin)]
    public class GraphicController : Controller
    {
        private readonly IAppUserService _appUserService;

        public GraphicController(IAppUserService appUserService)
        {
            _appUserService = appUserService;
        }

        public IActionResult Index()
        {
            TempData["Active"] = TempDataInfo.Graphic;
            return View();
        }

        public IActionResult MostCompleted()
        {
            var jsonString = JsonConvert.SerializeObject(_appUserService.GetMostCompletedStaff());
            return Json(jsonString);
        }
        public IActionResult MostWorking()
        {
            var jsonString = JsonConvert.SerializeObject(_appUserService.GetMostWorkingStaff());
            return Json(jsonString);
        }

    }
}

Erkan.ToDo.Web/Areas/Admin/Controllers/ImportanceController.cs
using AutoMapper;
using Erkan.ToDo.Business.Abstract;
using Erkan.ToDo.DTO.DTOs.ImportanceDtos;
using Erkan.ToDo.Entities.Concrete;
using Erkan.ToDo.Web.StringInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Erkan.ToDo.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = RoleInfo.Admin)]
    [Area(AreaInfo.Admin)]
    public class ImportanceController : Controller
    {
        private readonly IImportanceService _importanceService;
        private readonly IMapper _mapper;

        public ImportanceController(IImportanceService importanceService, IMapper mapper)
        {
            _importanceService = importanceService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            TempData["Active"] = TempDataInfo.Importance;

            return View(_mapper.Map<List<ImportanceListDto>>(_importanceService.GetAll()));
        }
        public IActionResult AddImportance()
        {
            TempData["Active"] = TempDataInfo.Importance;
            return View(new ImportanceAddDto());
        }
        [HttpPost]
        public IActionResult AddImportance(ImportanceAddDto model)
        {
            if (ModelState.IsValid)
            {
                _importanceService.Save(new Importance() {
                Definition = model.Definition
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }
        public IActionResult UpdateImportance(int id)
        {
            TempData["Active"] = TempDataInfo.Importance;

            return View(_mapper.Map<ImportanceUpdateDto>(_importanceService.GetId(id)));
        }
        [HttpPost]
        public IActionResult UpdateImportance(ImportanceUpdateDto model)
        {
            if (ModelState.IsValid)
            {
                _importanceService.Update(new Importance
                {
                    Id = model.Id,
                    Definition = model.Definition
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Erkan.ToDo.Web/Areas/Member/Controllers/HomeController.cs
using Erkan.ToDo.Business.Abstract;
using Erkan.ToDo.Entities.Concrete;
using Erkan.ToDo.Web.BaseControllers;
using Erkan.ToDo.Web.StringInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Erkan.ToDo.Web.Areas.Member.Controllers
{
    [Authorize(Roles = RoleInfo.Member)]
    [Area(AreaInfo.Member)]
    public class HomeController : BaseIdentityController
    {
        private readonly IReportService _reportService;
        private readonly ITaskService _taskService;
        private readonly INotificationService _notificationService;

        public HomeController(IReportService reportService, UserManager<AppUser> userManager, ITaskService taskService, INotificationService notificationService):base(userManager)
        {
            _reportService = reportService;
            _taskService = taskService;
            _notificationService = notificationService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await GetSignInUser();
            ViewBag.ReportCount = _reportService.GetReportCountByAppUserId(user.Id);

            ViewBag.CompletedTaskCount = _taskService.GetCompletedTaskCountByUserId(user.Id);

            ViewBag.IncompletedTaskCount = _taskService.GetIncompletedTaskCountByUserId(user.Id);

            ViewBag.UnreadNotification = _notificationService.GetUnreadCountByAppUserId(user.Id);

            TempData["Active"] = TempDataInfo.Homepage;
            return View();
        }
    }
}

Erkan.ToDo.Web/Areas/Member/Controllers/NotificationController.cs
using AutoMapper;
using Erkan.ToDo.Business.Abstract;
using Erkan.ToDo.DTO.DTOs.NotificationDtos;
using Erkan.ToDo.Entities.Concrete;
using Erkan.ToDo.Web.BaseControllers;
using Erkan.ToDo.Web.StringInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Erkan.ToDo.Web.Areas.Member.Controllers
{
    [Authorize(Roles = RoleInfo.Member)]
    [Area(AreaInfo.Member)]
    public class NotificationController : BaseIdentityController
    {
        private readonly INotificationService _notificationService;
        private readonly IMapper _mapper;

        public NotificationController(INotificationService notificationService, UserManager<AppUser> userManager, IMapper mapper):base(userManager)
        {
            _notificationService = notificationService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            TempData["Active"] = TempDataInfo.Notification;
            var user = await GetSignInUser();

            return View(_mapper.Map<List<NotificationListDto>>(_notificationService.GetUnread(user.Id)));
        }
        [HttpPost]
        public IActionResult Index(int id)
        {
            TempData["Active"] = TempDataInfo.Notification;
            var updateNotification = _notificationService.GetId(id);
            updateNotification.Statement = true;
            _notificationService.Update(updateNotification);
            return RedirectToAction("Index");
        }
    }
}

Erkan.ToDo.Web/Areas/Member/Controllers/ProfileController.cs
using AutoMapper;
using Erkan.ToDo.DTO.DTOs.AppUserDtos;
using Erkan.ToDo.Entities.Concrete;
using Erkan.ToDo.Web.BaseControllers;
using Erkan.ToDo.Web.StringInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Erkan.ToDo.Web.Areas.Member.Controllers
{
    [Authorize(Roles = RoleInfo.Member)]
    [Area(AreaInfo.Member)]
    public class ProfileController : BaseIdentityController
    {
        private readonly IMapper _mapper;

        public ProfileController(UserManager<AppUser> userManager, IMapper mapper):base(userManager)
        {
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            TempData["Active"] = TempDataInfo.Profile;
            var appUser = await GetSignInUser();


            return View(_mapper.Map<AppUserListDto>(appUser));
        }

        [HttpPost]
        public async Task<IActionResult> Index(AppUserListDto model, IFormFile picture)
        {
            if (ModelState.IsValid)
            {
                var updateUser = _userManager.Users.FirstOrDefault(I => I.Id == model.Id);
                if (picture != null)
                {
                    string extension = Path.GetExtension(picture.FileName);
                    string pictureName = Guid.NewGuid() + extension;
                    string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/" + pictureName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await picture.CopyToAsync(stream);
                    }

                    updateUser.Picture = pictureName;

                }

                updateUser.Name = model.Name;
                updateUser.SurName = model.SurName;
                updateUser.Email = model.Email;

                var result = await _userManager.UpdateAsync(updateUser);
                if (result.Succeeded)
                {
                    TempData["message"] = "Güncelleme işlemi başarıyla gerçekleşti";
                    return RedirectToAction("Index");
                }
                else
                {
                    ErrorAdd(result.Errors);
                }
            }
            return View(model);
        }
    }
}

Erkan.ToDo.Web/Areas/Member/Controllers/TaskController.cs
using AutoMapper;
using Erkan.ToDo.Business.Abstract;
using Erkan.ToDo.DTO.DTOs.TaskDtos;
using Erkan.ToDo.Entities.Concrete;
using Erkan.ToDo.Web.BaseControllers;
using Erkan.ToDo.Web.StringInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Erkan.ToDo.Web.Areas.Member.Controllers
{
    [Authorize(Roles = RoleInfo.Member)]
    [Area(AreaInfo.Member)]
    public class TaskController : BaseIdentityController
    {
        private readonly ITaskService _taskService;
        private readonly IMapper _mapper;


        public TaskController(ITaskService taskService, UserManager<AppUser> userManager, IMapper mapper):base(userManager)
        {
            _taskService = taskService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(int activePage=1)
        {
            TempData["Active"] = TempDataInfo.Task;
            var user = await GetSignInUser();
            var tasks =_mapper.Map<List<TaskListAllDto>>(_taskService.GetAllTableInCompleted(out int totalPage, user.Id, activePage));

            ViewBag.TotalPage = totalPage;
            ViewBag.ActivePage = activePage;

            return View(tasks);
        }
    }
}

Erkan.ToDo.Web/Areas/Member/Controllers/WorkOrderController.cs
using AutoMapper;
using Erkan.ToDo.Business.Abstract;
using Erkan.ToDo.DTO.DTOs.ReportDtos;
using Erkan.ToDo.DTO.DTOs.TaskDtos;
using Erkan.ToDo.Entities.Concrete;
using Erkan.ToDo.Web.BaseControllers;
using Erkan.ToDo.Web.StringInfo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Erkan.ToDo.Web.Areas.Member.Controllers
{
    [Authorize(Roles = RoleInfo.Member)]
    [Area(AreaInfo.Member)]
    public class WorkOrderController : BaseIdentityController
    {
        private readonly ITaskService _taskService;
        private readonly IReportService _reportService;
        private readonly INotificationService _notificationService;
        private readonly IMapper _mapper;
        public WorkOrderController(ITaskService taskService, UserManager<AppUser> userManager, IReportService reportService, INotificationService notificationService, IMapper mapper):base(userManager)
        {
            _taskService = taskService;
            _reportService = reportService;
            _notificationService = notificationService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            TempData["Active"] = TempDataInfo.WorkOrder;

            var user = await GetSignInUser();

            return View(_mapper.Map<List<TaskListAllDto>>(_taskService.GetAllTable(I => I.AppUserId == user.Id && !I.Statement)));
        }

        public IActionResult AddReport(int id)
        {
            TempData["Active"] = TempDataInfo.WorkOrder;
            var task = _taskService.GetImportanceById(id);

            ReportAddDto model = new ReportAddDto
            {
                TaskId = id,
                Task = task
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddReportAsync(ReportAddDto model)
        {
            if (ModelState.IsValid)
            {
                _reportService.Save(new Report
                {
                    TaskId = model.TaskId,
                    Describtion = model.Describtion,
                    Detail = model.Detail

                });

                var adminUserList = await _userManager.GetUsersInRoleAsync("Admin");

                var activeUser = await GetSignInUser();

                foreach (var admin in adminUserList)
                {
                    _notificationService.Save(new Notification
                    {
                        Explanation = $"{activeUser.Name} {activeUser.SurName} yeni bir rapor yazdı.",
                        AppUserId = admin.Id
                    });
                }


                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult UpdateReport(int id)
        {
            TempData["Active"] = TempDataInfo.WorkOrder;
            var report = _reportService.GetByTaskId(id);
            ReportUpdateDto model = new ReportUpdateDto
            {
                Id = report.Id,
                TaskId = report.TaskId,
                Task = report.Task,
                Describtion = report.Describtion,
                Detail = report.Detail
            };


            return View(model);
        }

        [HttpPost]
        public IActionResult UpdateReport(ReportUpdateDto model)
        {
            if (ModelState.IsValid)
            {
                var updateReport = _reportService.GetId(model.Id);

                updateReport.Describtion = model.Describtion;
                updateReport.Detail = model.Detail;

                _reportService.Update(updateReport);

                return RedirectToAction("Index");
            }
            return View(model);
        }

        public async Task<IActionResult> CompleteTaskAsync(int taskId)
        {
            var updatetask = _taskService.GetId(taskId);
            updatetask.Statement = true;
            _taskService.Update(updatetask);

            var adminUserList = await _userManager.GetUsersInRoleAsync("Admin");

            var activeUser = await GetSignInUser();

            foreach (var admin in adminUserList)
            {
                _notificationService.Save(new Notification
                {
                    Explanation = $"{activeUser.Name} {activeUser.SurName} vermiş olduğunuz bir görevi tamamladı.",
                    AppUserId = admin.Id
                });
            }

            return Json(null);
        }

    }

}

Erkan.ToDo.Web/Views/Shared/Components/Wrapper/Default.cshtml
@model AppUserListDto

@{
    string active = string.Empty;
    if (TempData["Active"] != null)
    {
        active = TempData["Active"].ToString();
    }
    //string active2 = TempData["Active"]?.ToString();
}

<div class="border border-right " id="sidebar-wrapper">
    <div class="sidebar-heading"><img src="~/img/@Model.Picture" alt="@Model.Name" style="height:10rem!important;" class="w-auto modal-dialog-centered img-thumbnail mx-auto" /></div>
    <div class="list-group list-group-flush">
        <div class="list-group list-group-flush">
            <a asp-action="Index" asp-controller="Home" class="list-group-item list-group-item-action @(active=="home"?"active":"")">
                <i class="fas fa-home mr-2"></i>Anasayfa
            </a>
            <a asp-action="Index" asp-controller="Task" class="list-group-item list-group-item-action @(active=="task"?"active":"")">
                <i class="fas fa-tasks mr-2"></i> Görev İşlemleri
            </a>
            <a asp-action="Index" asp-controller="Importance" class="list-group-item list-group-item-action @(active=="importance"?"active":"")">
                <i class="fas fa-exclamation-circle mr-2"></i>Aciliyet işlemleri
            </a>
            <a asp-action="Index" asp-controller="workOrder" class="list-group-item list-group-item-action  @(active=="workorder"?"active":"")">
                <i class="fas fa-business-time mr-2"></i>İş Emirleri
            </a>
            <a asp-action="Index" asp-controller="Graphic" class="list-group-item list-group-item-action @(active=="graphic"?"active":"")">
                <i class="fas fa-chart-pie mr-2"></i>Grafikler
            </a>
            <a asp-action="Index" asp-controller="Notification" class="list-group-item list-group-item-action @(active=="notification"?"active":"") position-relative ">
                <i class="fas fa-bell mr-2"></i>
                @if (ViewBag.NotificationCount > 0)
                {
                    <sub class="badge badge-primary badge-pill position-absolute" style="bottom:1rem!important; left:7.6rem!important">@ViewBag.NotificationCount</sub>
                }
                Bildirimler
            </a>
            <a asp-action="Index" asp-controller="Profile" class="list-group-item list-group-item-action  @(active=="profile"?"active":"")">
                <i class="fas fa-user mr-2"></i>Profil
            </a>
            <a asp-area="" asp-action="SignOut" asp-controller="Home" class="list-group-item list-group-item-action ">
                <i class="fas fa-sign-out-alt mr-2"></i>Çıkış
            </a>
        </div>
    </div>
</div>

Erkan.ToDo.Web/Views/Shared/Components/Wrapper/Member.cshtml
@model AppUserListDto

@{
    string active = string.Empty;
    if (TempData["Active"] != null)
    {
        active = TempData["Active"].ToString();
    }
    //string active2 = TempData["Active"]?.ToString();
}

<div class="border border-right " id="sidebar-wrapper">
    <div class="sidebar-heading"><img src="~/img/@Model.Picture" alt="@Model.Name" style="height:10rem!important;" class="w-auto modal-dialog-centered img-thumbnail" /></div>
    <div class="list-group list-group-flush">
        <a asp-action="Index" asp-controller="Home" class="list-group-item list-group-item-action @(active=="home"?"active":"")"><i class="fas fa-home mr-2"></i>Anasayfa</a>
        <a asp-action="Index" asp-controller="WorkOrder" class="list-group-item list-group-item-action @(active=="workOrder"?"active":"")"><i class="fas fa-arrow-circle-down mr-2"></i>Gelen İş Emirleri</a>
        <a asp-action="Index" asp-controller="Task" class="list-group-item list-group-item-action @(active=="task"?"active":"")"><i class="far fa-check-circle mr-2"></i>Tamamladığım İşler</a>
        <a asp-action="Index" asp-controller="Notification" class="list-group-item list-group-item-action @(active=="notification"?"active":"") position-relative ">
            <i class="fas fa-bell mr-2"></i>
            @if (ViewBag.NotificationCount > 0)
            {
                <sub class="badge badge-primary badge-pill position-absolute" style="bottom:1rem!important; left:7.6rem!important">@ViewBag.NotificationCount</sub>
            }
            Bildirimler
        </a>
        <a asp-action="Index" asp-controller="Profile" class="list-group-item list-group-item-action  @(active=="profile"?"active":"")"><i class="fas fa-user mr-2"></i>Profil</a>
        <a asp-area="" asp-action="SignOut" asp-controller="Home" class="list-group-item list-group-item-action "><i class="fas fa-sign-out-alt mr-2"></i>Çıkış</a>
    </div>
</div>